sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - curl
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"

script: 
- cd test/
- g++ -std=c++17 tests.cpp && ./tests


